### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by Tmpod** [pavlodvornikov/aiocfscrape#21]
Hey there!
I just recently tried this lib and I'm facing the same issue described on #2, on Python3.8. It seems you're passing the yarl URL object (used by aiohttp) directly into `urlparse`, while you should be "stringing" it. After I fixed that on a fork of mine, I also noticed `org_method` is not an attribute of the client session. After that, you were getting the request method via `resp.request.method` instead of `resp.method` (where `resp` is an aiohttp ClientResponse). Finally, I got an error about the lib not being able to solve the challenge, and after some digging, I noticed the lib doesn't seem to be quite up to date with `cfscrape` which you seem to mirror.
Are you also getting these results?

**Comment by Nachtalb** [comment]
I'll look into it on Sunday, thanks for the issue! 👍

**Comment by pystar1007** [comment]
Hello, @Nachtalb 
@Tmpod's commented is solved?

**Comment by DevL0rd** [comment]
Check my comments in #24. I solved the issues, but the cfscraper is too outdated. I pulled a fresh commit and am converting to aio tommorrow and it should be working by then.

**Comment by DevL0rd** [comment]
@Nachtalb I don't mind posting to completely updated version here tommorrow aswell and getting rid of my git repo at https://github.com/DevL0rd/aio-cloudflare-scrape

**Comment by Nachtalb** [comment]
@Tmpod I am currently updating this package and also incorporated your fixes. Though ATM it is a bit hard to actually test what I have written because I don't get the challenge with any site I try. The original non-aio package has a few tests, but they use mocking and haven't updated it for a year so I'd like to test it in a real-world scenario.

If you have a site where you get the challenge please tell me and you can test the stuff yourself as well with this branch: https://github.com/pavlodvornikov/aiocfscrape/tree/na/update-to-latest-cfscrape

CC/ @pypigstar1007 

@DevL0rd I see that you have copied the cfscrape one to one, which is IMHO not necessary because eg. a method like `create_scraper` (https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L350) is not needed because you can just do `session = aiocfscrape.CloudflareScraper()`, as it doesn't need additional setup.

**Comment by Nachtalb** [comment]
I'll close this in favour of #27. We will need to rewrite this package and thus the branch I talked about above can be ignored anyways...
